---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 6/7/2022 5:49 PM
---
local SoundButtonNode = class("SoundButtonNode", function()
    return cc.Node:create()
end)

local Sound = require("JumpingTheGantry.Sound")

local _allButtons = {}

function SoundButtonNode:ctor(part)
    table.insert(_allButtons, self)
    if (part) then
        self:addTo(part)
    end
    local soundBtn = ccui.Button:create("JumpingTheGantry/no_sound.png")
    soundBtn:addTo(self)
    local btnSize = soundBtn:getContentSize()
    --soundBtn:move(display.realCx + 300, display.realCy + 400)
    local noSoundSprite = display.newSprite("JumpingTheGantry/sound.png")
    noSoundSprite:addTo(soundBtn)
    --noSoundSprite:setVisible(Sound.isPause())
    noSoundSprite:move(btnSize.width / 2 + 10, btnSize.height / 2)
    soundBtn:addClickEventListener(function(sender)
        local soundPause = Sound.isPause()
        if soundPause then
            Sound.resume()
            --noSoundSprite:setVisible(false)
            for _, v in pairs(_allButtons) do
                v:_setNoSoundSpriteIsShow(true)
            end
        else
            Sound.pause()
            --noSoundSprite:setVisible(true)
            for _, v in pairs(_allButtons) do
                v:_setNoSoundSpriteIsShow(false)
            end
        end
        Sound.onClicked()
    end)
    self.noSoundSprite = noSoundSprite
    noSoundSprite:setVisible(not Sound.isPause())
end

function SoundButtonNode:_setNoSoundSpriteIsShow(isShow)
    self.noSoundSprite:setVisible(isShow)
end
return SoundButtonNode