---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 26/7/2022 3:23 PM
---

local BoomNode = class("BoomNode", function()
    return cc.Node:create()
end)
local Sound = require("KingKongWar.Sound")

function BoomNode:ctor(parent)
    --aaa()
    --local director = cc.Director:getInstance()
    --local scene = director:getRunningScene()
    --self:addTo(scene)
    --self:move(parent:convertToWorldSpace(cc.p(0, 0)))
    --self:setLocalZOrder(100)
    local sprite = display.newSprite('KingKongWar/images/gaming/icon_boom.png')
                          :setAnchorPoint(0.5, 0.5)
                          :addTo(self)

    local spriteSize = sprite:getContentSize()
    -- 刚体
    local body = cc.PhysicsBody:createCircle((spriteSize.height - 10) * 0.5)  -- 刚体大小，材质类型
    body:setCategoryBitmask(0x08) --00 00 01
    body:setContactTestBitmask(0x06)
    body:setCollisionBitmask(0x00)
    body:setGravityEnable(false)
    -- 设置球的刚体属性
    self:setPhysicsBody(body)   -- 设置球的刚体
    self:setPosition(cc.p(0, 0))
    --self:setScale(0, 0)
    --self:show()
    Sound.playBoom()
    self.sprite = sprite

    self.nodes = {}
    local contactListener = cc.EventListenerPhysicsContact:create()
    contactListener:registerScriptHandler(handler(self, self.onContactBegin), cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN)
    local eventDispatcher = self:getEventDispatcher()
    eventDispatcher:addEventListenerWithFixedPriority(contactListener, 1)
    --self:addTo(parent)

    local function onNodeEvent(event)
        if event == "enterTransitionFinish" then
            self:onEnterTransitionFinish()
        end
        print(event)
    end
    self:registerScriptHandler(onNodeEvent)
    self:scheduleUpdateWithPriorityLua(function()
        --dump(self:getPosition())
        self:setPosition(0, 0)
    end, 0)
    self:addTo(parent)
end

function BoomNode:onEnterTransitionFinish()
    self:setPosition(cc.p(0, 0))
    self:runAction(
            cc.Sequence:create(
            --cc.ScaleTo:create(0.1, 0),
            --        cc.CallFunc:create(function()
            --            --self:show()
            --            self:setOpacity(1)
            --        end),
            --cc.ScaleTo:create(0.5, 1),
            --cc.CallFunc:create(function()
            --    for v, node in ipairs(self.nodes) do
            --        print("node", node)
            --        local tag = node:getTag()
            --        --local isok, tag = pcall(handler(node, node.getTag))
            --        print(tag)
            --        if (tag == 11) then
            --            pcall(
            --                    function()
            --                        node:removeSelf()                            --墙壁
            --                    end
            --            )
            --        elseif tag == 10 then
            --            --玩家
            --            pcall(
            --                    function()
            --                        node:getParent().player_blood:setValue(node:getParent().player_blood.value - 1)
            --                    end
            --            )
            --        end
            --    end
            --end),
            --        cc.FadeTo:create(5, 1),
                    cc.DelayTime:create(1.5),
                    cc.CallFunc:create(function()
                        pcall(function()
                            for v, node in ipairs(self.nodes) do
                                print("node", node)
                                local tag = node:getTag()
                                local is_ok, tag = pcall(handler(node, node.getTag))
                                --local isok, tag = pcall(handler(node, node.getTag))
                                print(tag)
                                if (tag == 11) then
                                    pcall(
                                            function()
                                                node:removeSelf()                            --墙壁
                                            end
                                    )
                                elseif tag == 10 then
                                    --玩家
                                    pcall(
                                            function()
                                                node:getParent().player_blood:setValue(node:getParent().player_blood.value - 1)
                                            end
                                    )
                                end
                            end
                        end)
                        self:getParent():removeSelf(true)
                    end)
            )
    )
end

function BoomNode:onContactBegin(contact)
    local nodeA = contact:getShapeA():getBody():getNode()
    local nodeB = contact:getShapeB():getBody():getNode()

    if nodeA ~= self then
        return
    end

    local isAdd = false
    for k, v in ipairs(self.nodes) do
        if v == nodeB then
            isAdd = true
            break
        end
    end
    if not isAdd then
        table.insert(self.nodes, nodeB)
    end
    return false
end

return BoomNode

