---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 19/7/2022 12:01 PM
---

local MainScene = class("MainScene", ccui.Layout)

local Sound = require("KingKongWar.Sound")
local SoundNode = require("KingKongWar.SoundButtonNode")

local GameScene = require("KingKongWar.GameScene")
function MainScene:ctor()
    self:setContentSize(display.width, display.height)
    --self:setBackGroundColor(display.COLOR_RED)
    --self:setBackGroundColorType(ccui.LayoutBackGroundColorType.solid) --设置颜色

    ccui.ImageView:create("KingKongWar/images/bg.png")
        :setContentSize(display.width, display.height)
        :ignoreContentAdaptWithSize(false)
        :setAnchorPoint(0, 0)
        :addTo(self)

    SoundNode.new()
             :addTo(self)
             :move(200, display.height - 90)

    display.newSprite("KingKongWar/images/startLayer/logo.png")
           :addTo(self)
           :move(display.cx, display.cy + 100)

    ccui.Button:create("KingKongWar/images/startLayer/single_player_btn.png")
        :addTo(self)
        :move(display.cx - 200, display.cy - 200)
        :addClickEventListener(function()
        Sound.onClicked()
        GameScene:create(1)
        local Tools= require("JumpingTheGantry.Tools")
        print(Tools.And(0x06,0x03))
    end)

    ccui.Button:create("KingKongWar/images/startLayer/two_player_btn.png")
        :addTo(self)
        :move(display.cx + 200, display.cy - 200)
        :addClickEventListener(function()
        Sound.onClicked()
        GameScene:create(2)
    end)

end

return MainScene