---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 21/7/2022 6:37 PM
---

local NodeBanana = class("NodeBanana", cc.Node)

local BoomNode = require("KingKongWar.BoomNode")
local speed = 1-- 500000

function NodeBanana:ctor(playerArrowNode, parent)
    self:addTo(parent)
    self._isShow = true
    self.player = parent
    local value = playerArrowNode:getValues()
    local wordPos = playerArrowNode:convertToWorldSpace(cc.p(0, 0))
    local nodePos = parent:convertToNodeSpace(wordPos)
    -- 材质类型
    local MATERIAL_DEFAULT = cc.PhysicsMaterial(1, 0, 1)                      -- 密度、碰撞系数、摩擦力
    ---banana_bom
    local banana_bom = cc.Sprite:create("KingKongWar/images/gaming/banana_bomb.png")
    banana_bom:addTo(self)
    self:setTag(12)
    local bananaSize = banana_bom:getContentSize()
    -- 刚体
    local body = cc.PhysicsBody:createBox({ width = bananaSize.width, height = bananaSize.height / 2 }, MATERIAL_DEFAULT)  -- 刚体大小，材质类型
    body:setCategoryBitmask(0x01) --00 00 01
    body:setContactTestBitmask(0x16)
    body:setCollisionBitmask(0x01)
    -- 设置球的刚体属性
    self:setPhysicsBody(body)   -- 设置球的刚体
    self:setPosition(nodePos)
    --dump(value)
    --value = cc.pNormalize(value)
    --dump(value)
    body:applyImpulse(cc.pMul(cc.p(value.x * (self.player.player ~= 1 and -1 or 1), value.y), speed))
    --body:setVelocity
    --body:applyImpulse(cc.p(value.x * (self.player.player ~= 1 and -1 or 1) * speed, value.y * speed * 0.5))
    playerArrowNode:removeSelf()

    local contactListener = cc.EventListenerPhysicsContact:create()
    contactListener:registerScriptHandler(handler(self, self.onContactBegin), cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN)
    local eventDispatcher = cc.Director:getInstance():getEventDispatcher()
    eventDispatcher:addEventListenerWithFixedPriority(contactListener, 1)
    --self:scheduleUpdateWithPriorityLua(function()
    --    dump(self:getPosition())
    --
    --end, 0)

    --cc.Director:getInstance():getScheduler():scheduleScriptFunc(function()
    --    --self:removeNode(false)
    --    print("opoppopopo")
    --    dump(self:getPosition())
    --end)
end

function NodeBanana:removeNode()
    if not self._isShow then
        return
    end
    self._isShow = false
    --self:removeAllChildren()
    --display.newSprite('KingKongWar/images/gaming/icon_boom.png')
    --       :setAnchorPoint(0.5, 0.5)
    --       :addTo(self)
    self:getPhysicsBody():setEnabled(false)
    self:getPhysicsBody():removeFromWorld()
    --local wordPos = self:convertToWorldSpace(cc.p(0, 0))
    --local nodePos = self:convertToNodeSpace(wordPos)
    BoomNode:create(self)
    --:addTo(self)
    --:setPosition(nodePos)

end

function NodeBanana:onContactBegin(contact)
    local nodeA = contact:getShapeA():getBody():getNode()
    local nodeB = contact:getShapeB():getBody():getNode()
    if nodeA ~= self and nodeB ~= self then
        return
    end
    ---自己和其他发生了碰撞
    --- nodeB 设置成自己
    if nodeB ~= self then
        local temp = nodeA
        nodeA = nodeB
        nodeB = temp
    end

    --print("popop")
    local tagB = nodeB:getTag()
    local tagA = nodeA:getTag()
    --print(tagB, "碰撞了===", tagA)     --碰撞後的回調事件
    if (tagA == 10) or tagA == 11 or tagA == 12 then
        self:removeNode()
    end
    return false
end

return NodeBanana