---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 21/7/2022 6:37 PM
---

local NodeBanana = class("NodeBanana", cc.Node)
local speed = 10000

function NodeBanana:ctor(playerArrowNode, parent)
    self:addTo(parent)
    self.player = parent
    local value = playerArrowNode:getValues()
    local wordPos = playerArrowNode:convertToWorldSpace(cc.p(0, 0))
    local nodePos = parent:convertToNodeSpace(wordPos)
    -- 材质类型
    local MATERIAL_DEFAULT = cc.PhysicsMaterial(1, 0, 1)                      -- 密度、碰撞系数、摩擦力
    ---banana_bom
    local banana_bom = cc.Sprite:create("KingKongWar/images/gaming/banana_bomb.png")
    banana_bom:addTo(self)
    self:setTag(12)
    local bananaSize = banana_bom:getContentSize()
    -- 刚体
    local body = cc.PhysicsBody:createBox({ width = bananaSize.width, height = bananaSize.height / 2 }, MATERIAL_DEFAULT)  -- 刚体大小，材质类型
    body:setCategoryBitmask(0x01) --00 00 01
    body:setContactTestBitmask(0x06)
    --body:setCollisionBitmask(0x01)
    -- 设置球的刚体属性
    self:setPhysicsBody(body)   -- 设置球的刚体
    self:setPosition(nodePos)
    --body:applyImpulse(cc.pMul(cc.p(value.x * (self.player.player ~= 1 and -1 or 1), value.y), speed))
    body:applyImpulse(cc.p(value.x * (self.player.player ~= 1 and -1 or 1) * speed, value.y * speed * 1))
    playerArrowNode:removeSelf()

    local contactListener = cc.EventListenerPhysicsContact:create()
    contactListener:registerScriptHandler(handler(self, self.onContactBegin), cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN)
    local eventDispatcher = cc.Director:getInstance():getEventDispatcher()
    eventDispatcher:addEventListenerWithFixedPriority(contactListener, 1)

    --cc.Director:getInstance():getScheduler():scheduleScriptFunc(function()
    --    --self:removeNode(false)
    --    print("opoppopopo")
    --end, 5, false)
end

function NodeBanana:removeNode(isBoom, callback)
    self:removeAllChildren()
    if isBoom then
        --self:setPhysicsBody(body)
        local boom = display.newSprite('KingKongWar/images/gaming/icon_boom.png')
                            :addTo(self)
        self:getPhysicsBody():removeFromWorld()
        boom:setScale(0, 0)
        boom:runAction(
                cc.Sequence:create(
                        cc.ScaleTo:create(0.5, 1),
                        cc.CallFunc:create(function()
                            if callback then
                                pcall(
                                        callback
                                )
                            end
                        end),
                        cc.ScaleTo:create(0.5, 1.5),
                        cc.CallFunc:create(function()
                            boom:removeSelf()
                        end)

                )
        )
    else
        self:removeSelf()
    end
end

function NodeBanana:onContactBegin(contact)
    local nodeA = contact:getShapeA():getBody():getNode()
    local nodeB = contact:getShapeB():getBody():getNode()
    if nodeA ~= self and nodeB ~= self then
        return
    end
    ---自己和其他发生了碰撞
    --- nodeB 设置成自己
    if nodeB ~= self then
        local temp = nodeA
        nodeA = nodeB
        nodeB = temp
    end

    --print("popop")
    local tagB = nodeB:getTag()
    local tagA = nodeA:getTag()
    print(tagB, "碰撞了===", tagA)     --碰撞後的回調事件
    if (tagA == 10) or tagA == 11 then
        if self and self:isVisible() then
            self:removeNode(true, function()
                if tagA == 11 then
                    --墙壁
                    nodeA:removeSelf()
                elseif tagA == 10 then
                    --玩家
                    pcall(
                            function()
                                nodeA:getParent().player_blood:setValue(nodeA:getParent().player_blood.value - 1)
                            end
                    )
                end
            end)

        end

    end
    return false
end

return NodeBanana