---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 25/7/2022 4:09 PM
---

local OverScene = class("OverScene", function()
    return cc.Scene:create()
end)
local director = cc.Director:getInstance()
local Sound = require("KingKongWar.Sound")
local SoundNode = require("KingKongWar.SoundButtonNode")
function OverScene:ctor(winPlayer)
    self.layout = ccui.Layout:create()
                      :addTo(self)

    self.winPlayer = winPlayer
    self.layout:setContentSize(display.width, display.height)
    ccui.ImageView:create(string.format("KingKongWar/images/over/bg_player%s.png", winPlayer))
        :setContentSize(display.width, display.height)
        :ignoreContentAdaptWithSize(false)
        :setAnchorPoint(0, 0)
        :addTo(self.layout)
    SoundNode.new()
             :addTo(self.layout)
             :move(200, display.height - 90)
    ccui.ImageView:create(string.format("KingKongWar/images/over/icon_player%s.png", winPlayer))
        :ignoreContentAdaptWithSize(false)
        :addTo(self.layout)
        :move(400, 350)

    ccui.ImageView:create(string.format("KingKongWar/images/over/title_player%s.png", winPlayer))
        :ignoreContentAdaptWithSize(false)
        :addTo(self.layout)
        :move(display.width - 300, display.height - 300)

    local button = ccui.Button:create("KingKongWar/images/over/btn_reset.png")
                       :addTo(self.layout)
                       :move(display.width - 300, 160)

    button:addClickEventListener(function()
        Sound.onClicked()
        director:popToSceneStackLevel(1)
    end)
    director:pushScene(self)

end

return OverScene