---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 21/7/2022 11:16 AM
---
local PlayerArrowNode = class("PlayerArrowNode", function()
    return cc.Node:create()
end)
PlayerArrowNode.maxImageX = 65 * 2.1
PlayerArrowNode.minImageX = 65

PlayerArrowNode.runSpeed = 0.5
function PlayerArrowNode:ctor(distance)
    local image = ccui.ImageView:create("KingKongWar/images/gaming/icon_arrow.png")
    image:setScale9Enabled(true)
         :setAnchorPoint(0, 0.5)
         :addTo(self)
         :move(10, 0)
    image:setCapInsets(cc.rect(10, 25, 2, 2))
    self.image = image
    self.imageDefaultSize = image:getContentSize()

    self.nowSize = clone(self.imageDefaultSize)
    --PlayerArrowNode.minImageX = self.imageDefaultSize.width
    --PlayerArrowNode.maxImageX = PlayerArrowNode.minImageX * 3
    self._direction = 1
    if not distance then
        self:scheduleUpdateWithPriorityLua(handler(self, self._update), 0)
    else
        self._direction = distance / (display.width / 2)
        if (self._direction > 1) then
            self._direction = 1
        end
        self.nowSize = {
            width = PlayerArrowNode.maxImageX * self._direction,
            height = self.nowSize.height
        }
        if self.nowSize.width >= PlayerArrowNode.maxImageX then
            self._direction = -1
        elseif self.nowSize.width <= PlayerArrowNode.minImageX then
            self._direction = 1
        end
        self.image:setContentSize(self.nowSize)
    end
    --local text = ccui.Text:create()
    --text:addTo(self)
    --self.text = text
    --text:setString("0000")
end

function PlayerArrowNode:_update()
    self.nowSize = {
        width = self.nowSize.width + (self._direction * PlayerArrowNode.runSpeed),
        height = self.nowSize.height
    }
    if self.nowSize.width >= PlayerArrowNode.maxImageX then
        self._direction = -1
    elseif self.nowSize.width <= PlayerArrowNode.minImageX then
        self._direction = 1
    end
    self.image:setContentSize(self.nowSize)

    --self.text:setString(self:getRotation())
end

PlayerArrowNode.rotationConfig = 0.5
PlayerArrowNode.rotationMax = 90
function PlayerArrowNode:setStartTouchPosition(posY)
    self.startPosY = posY
end

function PlayerArrowNode:setTouchPosition(posY)
    self.rotateValue = posY - self.startPosY
    local rotate = self.rotateValue * PlayerArrowNode.rotationConfig
    if (rotate > PlayerArrowNode.rotationMax) then
        rotate = PlayerArrowNode.rotationMax
    elseif rotate < -PlayerArrowNode.rotationMax then
        rotate = -PlayerArrowNode.rotationMax
    end
    self:setRotation(-rotate)
end

function PlayerArrowNode:getValues()
    --local value = (PlayerArrowNode.minImageX / PlayerArrowNode.maxImageX) * (self.image:getContentSize().width - PlayerArrowNode.minImageX) -- * 1000000
    local value = (self.nowSize.width - PlayerArrowNode.minImageX) / (PlayerArrowNode.maxImageX - PlayerArrowNode.minImageX)
    value = value < 0.1 and 0 or value
    print(value, "0909009")
    value = value * 500000
    local rotate = self:getRotation()
    if (rotate < 0) then
        rotate = math.abs(rotate)
        local x = math.cos(math.pi / 180 * rotate)
        local y = math.sin(math.pi / 180 * rotate)
        return cc.pMul({ x = x, y = y }, value)
    elseif (rotate > 0) then
        rotate = math.abs(rotate)
        local x = math.cos(math.pi / 180 * rotate)
        local y = -math.sin(math.pi / 180 * rotate)
        return cc.pMul({ x = x, y = y }, value)
    else
        return cc.pMul({ x = 1, y = 0 }, value)
    end
end

return PlayerArrowNode