---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 7/7/2022 10:22 AM
---
local MiniGameController = class("MiniGameController")
local MINIGAMECONTROLLER_Z_UI_ORDER = 10
local SoundBtn = require("PartyWheel.SoundButtonNode")
local Sound = require("PartyWheel.Sound")
local RunAllTemp = {
    "gongbei", --公杯
    'suoyourenhe', --所有人喝
    "youshoubianhe", --右手边喝
    "zhidingyigerenhe", --指定一个人喝
    'zuoshoubianhe', --左手边喝
    'zijihe', -- 自己喝
}
function MiniGameController:ctor(parent, startLayout, resetLayout)
    self.mainNode = parent
    ccui.Scale9Sprite:create("PartyWheel/image/bg.jpg")
        :setCapInsets(CCRectMake(750 * 0.5, 408, 1, 990))
        :setContentSize(display.realWidth, display.realHeight)
        :setAnchorPoint(cc.p(0.5, 0.5))
        :addTo(parent)
        :setLocalZOrder(-10)
        :move(display.realCx, display.realCy)

    self.gameNode = cc.Node:create()
                      :setAnchorPoint(cc.p(0.5, 0.5))
                      :addTo(self.mainNode)
                      :move(display.realCx, display.realCy)
    self.gameNode:hide()

    self.uiNode = cc.Node:create()
                    :setAnchorPoint(cc.p(0.5, 0.5))
                    :move(display.realCx, display.realCy)

    self.uiNode:addTo(self.mainNode)
    self.uiNode:setLocalZOrder(MINIGAMECONTROLLER_Z_UI_ORDER)
    self.startLayout = startLayout.new(self.uiNode, handler(self, MiniGameController.goToGame))
    self.resetLayout = resetLayout.new(self.uiNode, handler(self, MiniGameController.goToGame), handler(self, MiniGameController.onHome))
    self.resetLayout:hideLayout()

    SoundBtn.new(self.gameNode)
            :move(cc.p(-display.realCx + 100, display.realCy - 150))

    local contentNode = cc.Node:create()
                          :addTo(self.gameNode)
    self.gameAniNode = cc.Sprite:create("PartyWheel/image/game_icon_3.png")
                         :setAnchorPoint(cc.p(0.5, 0.5))
                         :addTo(contentNode)
                         :setScale(display.width / CC_DESIGN_RESOLUTION.width)

    local gameAniContentSize = self.gameAniNode:getContentSize()
    cc.Sprite:create("PartyWheel/image/game_icon_1.png")
      :setAnchorPoint(cc.p(0.5, 0.5))
      :addTo(contentNode)
      :move(cc.p(0, (gameAniContentSize.height / 2) * (display.width / CC_DESIGN_RESOLUTION.width)))
      :setLocalZOrder(-10)
      :setScale(display.width / CC_DESIGN_RESOLUTION.width)

    cc.Sprite:create("PartyWheel/image/pointer_icon.png")
      :setAnchorPoint(cc.p(0.5, 0.5))
      :addTo(contentNode)
      :setScale(display.width / CC_DESIGN_RESOLUTION.width)

    ccui.Button:create("PartyWheel/image/btn_start.png")
        :setAnchorPoint(cc.p(0.5, 0.5))
        :addTo(self.gameNode)
        :move(cc.p(0, -display.realCy + (300 * (display.width / CC_DESIGN_RESOLUTION.width))))
        :setScale(display.width / CC_DESIGN_RESOLUTION.width)

        :addClickEventListener(function(sender)
        Sound.onClicked()
        self:_runGame()
    end)
    self.nowSelect = 1
end

function MiniGameController:_runGame()
    if (self.isRuing) then
        return
    end
    self.isRuing = true
    self.nowSelect = math.random(1, #RunAllTemp)

    --转的圈数
    local randomCount = math.random(7, 10)
    --动画时长 随机
    local randomDuration = math.random(3, 7)

    --一共需要旋转的度数
    local nowRotate = (360 / #RunAllTemp) * (self.nowSelect - 1)
    local allPi = 360 * randomCount-- + (360 / #RunAllTemp) * self.nowSelect -- (360 - (self.gameAniNode:getRotation() % 360))
    allPi = allPi + nowRotate
    --allPi = allPi + (-previous)
    ---开始旋转前需要重置旋转的角度
    --self.gameAniNode:setRotation(0)

    self.gameAniNode:runAction(
            cc.Spawn:create(
                    cc.Sequence:create(
                            cc.DelayTime:create(0.5),
                            cc.CallFunc:create(function()
                                Sound.playEffectWheelSpin()
                            end),
                            cc.DelayTime:create(randomDuration - 1),
                            cc.CallFunc:create(function()
                                Sound.playEffectWheelStop()
                            end)
                    ),
                    cc.Sequence:create(
                            cc.EaseInOut:create(
                                    cc.RotateTo:create(randomDuration, allPi), randomDuration),
                            cc.CallFunc:create(function()
                                self.gameAniNode:setRotation(nowRotate)
                            end),
                            cc.DelayTime:create(0.5), cc.CallFunc:create(function()
                                local select = RunAllTemp[self.nowSelect]
                                print("over " .. select)
                                self.resetLayout:showLayout(select)
                                self.isRuing = false
                            end)
                    )
            )
    )
end

function MiniGameController:goToGame()
    self.startLayout:hide()
    self.gameNode:show()
    self.resetLayout:hideLayout()
end

function MiniGameController:onHome()
    print("打开主页")
end

return MiniGameController