# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyLuaGame-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLuaGame-desktop

end

target 'MyLuaGame-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLuaGame-mobile
  pod 'Google-Mobile-Ads-SDK'

end
