---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 4/8/2022 3:46 PM
---

local GameScene = class("GameScene", function()
    return cc.Scene:createWithPhysics()
end)
local scale_value = display.width / CC_DESIGN_RESOLUTION.width
local SoundButtonNode = require("SoftFudgeCandy.SoundButtonNode")

local CandyNode = require("SoftFudgeCandy.CandyNode")

local initCandyCount = 40
function GameScene:ctor()
    local rotateNode = cc.Node:create()
    rotateNode:addTo(self)
    rotateNode:setContentSize(cc.size(display.height, display.width))
    rotateNode:setAnchorPoint(cc.p(0.5, 0.5))
    rotateNode:setRotation(-90)
    rotateNode:move(display.cx, display.cy)
    self.rotateNode = rotateNode

    self.bg = ccui.ImageView:create("SoftFudgeCandy/images/game/bg.png")
                  :setContentSize(display.realWidth, display.realHeight)
                  :setScale9Enabled(true)
                  :setCapInsets({ x = 135, y = 135, width = 390, height = 750 })
                  :setAnchorPoint(0.5, 0.5)
                  :addTo(self.rotateNode)
                  :move(display.realCx, display.realCy)

    self.candyNodes = cc.Node:create()
                        :addTo(self.bg)
    local scoreBg = display.newSprite("SoftFudgeCandy/images/game/score_bg.png")
                           :setScale(scale_value)
                           :addTo(self.bg)
                           :move(display.realCx, display.realHeight - 120 * (display.height / CC_DESIGN_RESOLUTION.height))

    --local scoreText = ccui.TextBMFont:create()
    --                      :setAnchorPoint(0, 0.5)
    --                      :addTo(scoreBg)
    --                      :setPosition(cc.p(160, 40))
    --                      :setScale(scale_value)
    --scoreText:setFntFile("SoftFudgeCandy/images/game/score_text.fnt")
    --scoreText:setString(0)
    --self.scoreText = scoreText

    local scoreText = cc.Label:createWithTTF("0", "SoftFudgeCandy/images/game/score_text.ttf", 30)
                        :setAnchorPoint(0, 0.5)
                        :addTo(scoreBg)
                        :setPosition(cc.p(160, 33))
    scoreText:setTextColor(cc.c3b(0xf7, 0x9d, 0xff))
    self.scoreText = scoreText

    SoundButtonNode:create()
                   :addTo(scoreBg)
    --:setScale(scale_value)
                   :move(-65 * scale_value, 43 * scale_value)

    self:InitPhysicsWord()

    ccui.Button:create("SoftFudgeCandy/images/game/score_bg.png")
        :addTo(self.bg)
        :addClickEventListener(function()
        --self:removeCandyNode({ id = 12 })
        self:gameOver()
    end)

    --newCandyNode = function()
    --    CandyNode:create()
    --             :addTo(self.bg)
    --             :move(math.random(90, display.realWidth - 90), display.realHeight - 75)
    --             :addClickEventListener(function()
    --        newCandyNode()
    --    end)
    --end
    --newCandyNode()

    --self:TestPhysics()
    --self:TestPhysics()
    --self:TestPhysics()
    --self:TestPhysics()
    --self:TestPhysics()
    --self:TestPhysics()

    self.removeTimer = 0
    self.changeIsOverHandle = cc.Director:getInstance():getScheduler():scheduleScriptFunc(function()
        print("检测游戏是否结束")
        local children = self.candyNodes:getChildren()
        for _, candyNode in ipairs(children) do
            local body = candyNode:getPhysicsBody()
            if body and body:getVelocity().x > 10 then
                print("有在运动的")
                return
            end
        end

        for _, candyNode in ipairs(children) do
            local temp = {}
            temp = candyNode:getAllCandyNodes(temp)
            if #temp > 1 then
                print("有挨着一样的")
                self.removeTimer = self.removeTimer + 1
                if self.removeTimer >= 3 then
                    for _, node in pairs(temp) do
                        node:runAction(cc.Sequence:create(
                                cc.FadeTo:create(0.5, 255 * 0.7),
                                cc.FadeTo:create(0.5, 255),
                                cc.FadeTo:create(0.5, 255 * 0.7),
                                cc.FadeTo:create(0.5, 255),
                                cc.FadeTo:create(0.5, 255 * 0.7),
                                cc.FadeTo:create(0.5, 255)
                                
                        ))
                    end
                end
                return
            end
        end
        self:gameOver()
    end, 5, false)

end

---@private 初始化物理世界
function GameScene:InitPhysicsWord()
    --self:getPhysicsWorld():setDebugDrawMask(cc.PhysicsWorld.DEBUGDRAW_ALL) -- cc.PhysicsWorld. DEBUGDRAW_ALL 显示包围盒 cc.PhysicsWorld.DEBUGDRAW_NONE 不显示包围盒

    local gravity = cc.p(98, 0)
    self:getPhysicsWorld():setGravity(gravity)

    local edgeBox = cc.PhysicsBody:createEdgeBox({
        width = display.realWidth - 90 * 2, height = display.realHeight + 200,
    }, cc.PHYSICSBODY_MATERIAL_DEFAULT, 2)
    edgeBox:setPositionOffset(cc.p(-75 - 200 / 2, 0))
    self.bg:setPhysicsBody(edgeBox)

    local tempEdgeBox = cc.PhysicsShapeEdgeBox:create({
        width = (display.realWidth - 90 * 2), height = display.realHeight * 0.32,
    }, cc.PHYSICSBODY_MATERIAL_DEFAULT, 2
    )
    tempEdgeBox:setTag(2)
    edgeBox:addShape(tempEdgeBox)

    CandyNode.setParent(self.candyNodes)
    for index = 0, initCandyCount do
        CandyNode:create()
    end
    local delayDoSomething = function(callback, time)
        local handle
        handle = cc.Director:getInstance():getScheduler():scheduleScriptFunc(function()
            cc.Director:getInstance():getScheduler():unscheduleScriptEntry(handle)
            callback()
        end, time, false)

        return handle
    end
    delayDoSomething(function()
        edgeBox:removeShape(2, true)
    end, 0.2)
end

function GameScene:TestPhysics()
    ---- 材质类型
    --local MATERIAL_DEFAULT = cc.PhysicsMaterial(100, 0, 0.9)                      -- 密度、碰撞系数、摩擦力
    --
    ---- 球
    --local banana_bom = cc.Sprite:create("SoftFudgeCandy/images/game/Candys/1.png")
    --
    ---- 刚体
    --local body = cc.PhysicsBody:createCircle(banana_bom:getContentSize().width * 0.5, MATERIAL_DEFAULT)  -- 刚体大小，材质类型
    --
    ---- 设置球的刚体属性
    --banana_bom:setPhysicsBody(body)   -- 设置球的刚体
    --self.bg:addChild(banana_bom)
    --banana_bom:move(display.realCx, display.realCy)

    -- 触摸事件
    local function onTouchBegan(touch, event)
        local location = touch:getLocation()
        local arr = self:getPhysicsWorld():getShapes(location)

        local body = nil
        for _, obj in ipairs(arr) do
            if obj:getBody() then
                body = obj:getBody()
            end
        end

        if body then
            local mouse = cc.Node:create()
            local physicsBody = cc.PhysicsBody:create(PHYSICS_INFINITY, PHYSICS_INFINITY)
            mouse:setPhysicsBody(physicsBody)
            physicsBody:setDynamic(false)
            mouse:setPosition(location)
            self.bg:addChild(mouse)
            local joint = cc.PhysicsJointPin:construct(physicsBody, body, location)
            joint:setMaxForce(5000.0 * body:getMass())
            cc.Director:getInstance():getRunningScene():getPhysicsWorld():addJoint(joint)
            touch.mouse = mouse

            return true
        end

        return false
    end

    local function onTouchMoved(touch, event)
        if touch.mouse then
            touch.mouse:setPosition(touch:getLocation())
        end
    end

    local function onTouchEnded(touch, event)
        if touch.mouse then
            self.bg:removeChild(touch.mouse)
            touch.mouse = nil
        end
    end
    local touchListener = cc.EventListenerTouchOneByOne:create()
    touchListener:registerScriptHandler(onTouchBegan, cc.Handler.EVENT_TOUCH_BEGAN)
    touchListener:registerScriptHandler(onTouchMoved, cc.Handler.EVENT_TOUCH_MOVED)
    touchListener:registerScriptHandler(onTouchEnded, cc.Handler.EVENT_TOUCH_ENDED)
    local eventDispatcher = self.bg:getEventDispatcher()
    eventDispatcher:addEventListenerWithSceneGraphPriority(touchListener, self.bg)
end

---@public removeCandyNode 合并删除的node
function GameScene:removeCandyNode(candyNode)
    print(candyNode.id, "removeCandyNode")
    self.removeTimer = 0
    if candyNode.id < CandyNode.MaxId then
        local value = (self.scoreText.number or 0) + math.pow(2, candyNode.id)
        self.scoreText:setString(value)
        self.scoreText.number = value
        CandyNode:create()
    else
        ---爆炸
        local value = (self.scoreText.number or 0) + 2048
        self.scoreText:setString(value)
        self.scoreText.number = value
        for k, node in ipairs(self.candyNodes:getChildren()) do
            node:removeSelf()
        end
        local boom = display.newSprite("SoftFudgeCandy/images/game/boom.png")
                            :addTo(self.rotateNode)
                            :setScale(0)
                            :move(display.realCx, display.realCy + 150 * scale_value)
        boom:runAction(
                cc.Sequence:create(
                        cc.ScaleTo:create(2, 1.3),
                        cc.CallFunc:create(function()
                            for index = 0, initCandyCount do
                                CandyNode:create()
                            end
                        end),
                        cc.ScaleTo:create(1, 0.2),
                        cc.CallFunc:create(handler(boom, boom.removeSelf))
                )
        )
    end
end

---@public gameOver 结束游戏
function GameScene:gameOver()
    if (self.changeIsOverHandle) then
        cc.Director:getInstance():getScheduler():unscheduleScriptEntry(self.changeIsOverHandle)
        self.changeIsOverHandle = nil
    end
    cc.Director:getInstance():replaceScene(require("SoftFudgeCandy.OverScene"):create(self.scoreText.number))
    print("结束游戏")
end

return GameScene