---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 4/8/2022 3:04 PM
---

local MainScene = class("MainScene", ccui.Layout)

local Sound = require("SoftFudgeCandy.Sound")
local SoundButtonNode = require("SoftFudgeCandy.SoundButtonNode")
local scale_value = display.width / CC_DESIGN_RESOLUTION.width

local GameScene = require("SoftFudgeCandy.GameScene")
function MainScene:ctor()
    local rotateNode = cc.Node:create()
    rotateNode:addTo(self)
    rotateNode:setContentSize(cc.size(display.height, display.width))
    rotateNode:setAnchorPoint(cc.p(0.5, 0.5))
    rotateNode:setRotation(-90)
    rotateNode:move(display.cx, display.cy)
    self.rotateNode = rotateNode
    display.realWidth = display.height
    display.realHeight = display.width
    display.realCx = display.cy
    display.realCy = display.cx

    ccui.ImageView:create("SoftFudgeCandy/images/start/bg.png")
        :setContentSize(display.realWidth, display.realHeight)
        :setScale9Enabled(true)
        :setCapInsets({ x = 100, y = 200, width = 500, height = 800 })
        :setAnchorPoint(0.5, 0.5)
        :addTo(self.rotateNode)
        :move(display.realCx, display.realCy)

    display.newSprite("SoftFudgeCandy/images/start/logo.png")
           :addTo(self.rotateNode)
           :setScale(scale_value)
           :move(display.realCx, display.realCy + (100 * scale_value))

    ccui.Button:create("SoftFudgeCandy/images/start/btn_start.png")
        :addTo(self.rotateNode)
        :setScale(scale_value)
        :move(display.realCx, 200 * scale_value)
        :addClickEventListener(function(sender)
        Sound.onClicked()
        cc.Director:getInstance():pushScene(GameScene:create())
    end)
    SoundButtonNode:create()
                   :addTo(self.rotateNode)
                   :setScale(scale_value)
                   :move(100 * scale_value, display.realHeight - 100 * scale_value)
    Sound.playBgMusic()
end

function MainScene:startGame()

end

return MainScene