---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 5/8/2022 3:12 PM
---

local OverScene = class("OverScene", function()
    return cc.Scene:create()
end)
local scale_value = display.width / CC_DESIGN_RESOLUTION.width
local SoundButtonNode = require("SoftFudgeCandy.SoundButtonNode")
local Sound = require("SoftFudgeCandy.Sound")

function OverScene:ctor(score)
    local rotateNode = cc.Node:create()
    rotateNode:addTo(self)
    rotateNode:setContentSize(cc.size(display.height, display.width))
    rotateNode:setAnchorPoint(cc.p(0.5, 0.5))
    rotateNode:setRotation(-90)
    rotateNode:move(display.cx, display.cy)
    self.rotateNode = rotateNode

    self.bg = ccui.ImageView:create("SoftFudgeCandy/images/over/bg.png")
                  :setContentSize(display.realWidth, display.realHeight)
                  :setScale9Enabled(true)
                  :setCapInsets({ x = 135, y = 135, width = 390, height = 750 })
                  :setAnchorPoint(0.5, 0.5)
                  :addTo(self.rotateNode)
                  :move(display.realCx, display.realCy)

    local content = display.newSprite("SoftFudgeCandy/images/over/content.png")
                           :addTo(self.bg)
                           :setScale(scale_value)
                           :move(display.realCx, display.realCy)

    local btn_reset = ccui.Button:create("SoftFudgeCandy/images/over/btn_reset.png")
                          :addTo(self.bg)
                          :setScale(scale_value)
                          :move(display.realCx, 200 * scale_value)
    btn_reset:addClickEventListener(function()
        print("重新游戏")
        Sound.onClicked()
        cc.Director:getInstance():popToSceneStackLevel(1)
    end)
    local contentSize = content:getContentSize()
    display.newSprite("SoftFudgeCandy/images/over/title.png")
           :setAnchorPoint(0.5, 1)
           :addTo(content)
           :move(contentSize.width / 2, contentSize.height - 150)

    display.newSprite("SoftFudgeCandy/images/over/score_title.png")
           :setAnchorPoint(0.5, 1)
           :addTo(content)
           :move(contentSize.width / 2, contentSize.height - 280)

    local score_bg = display.newSprite("SoftFudgeCandy/images/over/score_bg.png")
                            :setAnchorPoint(0.5, 1)
                            :addTo(content)
                            :move(contentSize.width / 2, contentSize.height - 380)
    local score_size = score_bg:getContentSize()
    local scoreText = cc.Label:createWithTTF(score or "0", "SoftFudgeCandy/images/game/score_text.ttf", 30)
                        :setAnchorPoint(0.5, 0.5)
                        :addTo(score_bg)
                        :setPosition(cc.p(score_size.width / 2, score_size.height / 2))
    scoreText:setTextColor(cc.c3b(0xf7, 0x9d, 0xff))
    self.scoreText = scoreText

    SoundButtonNode:create()
                   :addTo(self.bg)
                   :setScale(scale_value)
                   :move(100 * scale_value, display.realHeight - 100 * scale_value)
end

return OverScene