---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lucus.
--- DateTime: 4/7/2022 11:50 AM
---
local MiniGameController = class("MiniGameController")
local LevelSelection = require("GuessTheIdiom.LevelSelection")

local Sound = require("GuessTheIdiom.Sound")
local ButtonSound = require("GuessTheIdiom.SoundButtonNode")
function MiniGameController:ctor(mainNode)
    self.mainNode = mainNode
    self.levelSelectionNode = LevelSelection:create(self.mainNode)
    self.levelSelectionNode:setPosition(display.cx, display.cy)
    self:initScene()
    self.gameNode:hide()
end

function MiniGameController:start()
    self.gameNode:hide()
end

function MiniGameController:initScene()
    self.gameNode = cc.Node:create()
                      :setAnchorPoint(cc.p(0.5, 0.5))
                      :addTo(self.mainNode)
                      :setPosition(display.cx, display.cy)
    ccui.Scale9Sprite:create("GuessTheIdiom/images/start_panel_bg.png")
    --:setCapInsets(CCRectMake(750 * 0.5, 408, 1, 990))
        :setContentSize(display.width, display.height)
    --:setAnchorPoint(cc.p(0, 0))
        :addTo(self.mainNode)
        :setLocalZOrder(-10)
        :setPosition(display.cx, display.cy)

    display.newSprite("GuessTheIdiom/images/logo.png")
           :setAnchorPoint(cc.p(0.5, 0.5))
           :addTo(self.gameNode)
           :setPosition(0, 100)

    ccui.Button:create("GuessTheIdiom/images/btn_start.png")
        :setAnchorPoint(cc.p(0.5, 0.5))
        :addTo(self.gameNode)
        :setPosition(0, -250)
        :addClickEventListener(function(sender)
        Sound.onClicked()
        self:start()
        print("点击了开始游戏")
    end)

    ButtonSound:create(self.gameNode)
               :setPosition(display.cx - 200, display.cy - 100)
end

return MiniGameController